services:
  webapp:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:8000 --workers=2 --timeout=300 reveal.app:app
    volumes:
      - ./services/web/:/app
      - upload_volume:/app/uploads/
      - report_volume:/app/reports/
      - update-data:/app/update-data/
    env_file:
      - ./services/web/webapp.env
    depends_on:
      - db
  webapi:
    build: ./services/api
    command: gunicorn --bind 0.0.0.0:8001 reveal.api:app
    volumes:
      - ./services/api/:/app
    env_file:
      - ./services/web/webapp.env
    depends_on:
      - db
      - webapp
  db:
    build: ./services/db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: ./services/nginx
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
      - "8443:8443"
    depends_on:
      - webapp
      - webapi
volumes:
  postgres_data:
  upload_volume:
  report_volume:
  update-data:
  ssl_volume:
